### ISSUE TITLE
What Can I do about Deathlog?

### ISSUE THREAD

**Issue by VoidlsCool** [glisco03/deathlog#10]
Anytime I Try To Open The Mod It Always Says " An Error Startup Prevented Minecraft From Starting" What Caused It Was Deathlog. I Have Been Trying To Play For A Week Now And Nothing. Any Help?

**Comment by gliscowo** [comment]
Without a crash report I can't really help you here - this could be caused by literally anything
Cheers

**Comment by gliscowo** [comment]
Have you since made any new discoveries about this issue?
