### ISSUE TITLE
[Feature Request] Add death recovery item check mark

### ISSUE THREAD

**Issue by EGOIST1372** [glisco03/deathlog#12]
Add death recovery item check mark
what I mean is when you die death log says you had this items and this is the coordinates you lost your items.
now it would be great if when player goes back to the death location and recovers all its items a sound cue or a check mark icon shows in the left side of the experience bar that indicates you recovered all of your lost items on death.(if all items in inventory match or exceed the number on death then should give the recovery signal)
thanks in advance <3

**Comment by EGOIST1372** [comment]
or just show a check mark on each item in the deathlog menu on items that recovered fully
its a very cool idea

**Comment by gliscowo** [comment]
I do agree that this would be a very neat feature to have, but for the time being it's simply out of scope. Adding this would require a significant amount of extra code, given that we would want a solution that's hard to break - which is obviously desirable. I'm gonna keep this in mind as I might come back to it in the future, but for now I'll close this as not planned
Cheers
