### ISSUE TITLE
[Suggestion] Command to rob other player's deaths (OP ONLY)

### ISSUE THREAD

**Issue by Sebas-Re** [glisco03/deathlog#19]
Hello!

For moderation purposes, I would like to suggest a way to restore another player's death entry into my own inventory intead of theirs.

Usage for this would be: If a player loses a certain item(s) due to a server crash, being able to give that item(s) back without restoring the whole death entry into their inventory

**Comment by gliscowo** [comment]
Such a feature is not necessary, as you can already give yourself single items from a snapshot while in creative mode - be it your own death or somebody else's. Granted, this isn't documented very well, but the tooltip of the items shows it while looking at a death entry.

I hope this brings you some insight (even if it comes horribly late, for which I apologize)
Cheers
