### ISSUE TITLE
Crash when opening statistics

### ISSUE THREAD

**Issue by Fabian42** [glisco03/deathlog#20]
Minecraft consistently crashes every time I click "Statistics" when DeathLogger is installed and never without. I don't know which version introduced the issue, but could binary-search that if that's helpful.

[crash-2023-02-05_22.08.23-client.txt](https://github.com/gliscowo/deathlog/files/10613812/crash-2023-02-05_22.08.23-client.txt)

**Comment by BasiqueEvangelist** [comment]
That version doesn't seem to support 1.19.3.

**Comment by Fabian42** [comment]
Oh, you're right, I must have missed it when updating all my mods! Why does it let me start the game then?

**Comment by Fabian42** [comment]
Works with the latest version and the amazingly named owo-lib.
