### ISSUE TITLE
Giving items doesn't work

### ISSUE THREAD

**Issue by Fabian42** [glisco03/deathlog#22]
I tried all the mouse buttons and lots of the keyboard buttons, all with various modifier keys, in Survival and Creative, with an OP account and the non-OP account that died, nothing works. Seems like this feature is just broken in 0.3.1.

**Comment by gliscowo** [comment]
Thanks for pointing this out, it's now been fixed in [0.3.2](https://modrinth.com/mod/deathlog/version/7leIrcSH)
Cheers
