### ISSUE TITLE
[1.18.1] Deathlog Restore doesn't work on dedicated servers

### ISSUE THREAD

**Issue by lizfinite** [glisco03/deathlog#3]
Mods installed for test:
- deathlog-0.2.4+1.18
- fabric-api-0.45.0+1.18
- modmenu-3.0.1
- trinkets-3.1.0

Steps for reproduction:
- connect to dedicated server with deathlog, have op/be in creative
- have inventory and die
- Open death log, and shift-click the restore icon
- Return to game and see inventory is not restored
- Check log
Expected: will restore like single player
Actual: does not restore, outputs error in log

Here's the server log: [https://pastebin.com/qfAb2QEs](https://pastebin.com/qfAb2QEs)

**Comment by gliscowo** [comment]
This is actually to be expected, as you have to use `/deathlog view <playername>` on a dedicated server to get the correct screen from which you can restore the death infos for a given player. In you case, you did still discover a bug because when opening the client-side screen on a dedicated server you should not be able to restore, so thanks for reporting
Cheers

**Comment by lizfinite** [comment]
Ah, I see. I must've missed the information regarding it requiring a command on server somewhere, apologies.
Just ran the updated build. As a user, I feel like if I have Operator and open the client side screen while in multiplayer; it should be equivalent to executing `/deathlog view @p`, for a more seamless experience. Feels a like an weird extra step if I'm able to open the client side menu without a restore button, but typing the command and opening it provides the exact same menu with restore buttons.  Having the command available to see/restore others that are not operator is great though, so glad to have it.

**Comment by gliscowo** [comment]
You see, the two screens you get from your client and the server are not equivalent at all. One of them has the deaths you client has tracked globally, for every world and server versus the other one which just shows the server-side log which is tracked by the server for each player individually and requires DeathLog to be installed on the server as well as operator permissions. So while I do see where you're coming from, it'll stay how it is to provide a clear separation of concerns.
