### ISSUE TITLE
Add deathlog button to better statistics screen

### ISSUE THREAD

**Issue by ItsProfessional** [glisco03/deathlog#30]
[Better Statistics Screen](https://modrinth.com/mod/better-stats)

**Comment by gliscowo** [comment]
While I appreciate that this is technically missing functionality, it would most likely make much more sense to be implemented on their side instead of DeathLog directly - you might want to consider opening an issue with them instead. Further, while the button is no doubt useful sometimes, it's not required as you can always open the screen using the provided keybind instead

Cheers

**Comment by ItsProfessional** [comment]
> While I appreciate that this is technically missing functionality, it would most likely make much more sense to be implemented on their side instead of DeathLog directly

Why? Better Statistics Screen is unrelated to deathlog. Them implementing support for tens or hundreds of mods doesn't make sense. It should be deathlog that adds support IMHO

**Comment by BasiqueEvangelist** [comment]
> Why? Better Statistics Screen is unrelated to deathlog. Them implementing support for tens or hundreds of mods doesn't make sense. It should be deathlog that adds support IMHO

DeathLog also isn't related to Better Statistics Screen. Why should we have to add support for mods that literally entirely replace *vanilla* screens?

**Comment by ItsProfessional** [comment]
Because deathlog adds to the screen. Better Statistics reimplements the screen. They don't have a reason to add non-vanilla things in their reimplementation. Mods that modify the vanilla screen should also modify the better statistics screen

**Comment by gliscowo** [comment]
And what if another mod comes around? Are we also supposed to modify the Better Statistics Screen Plus and Overhauled Statistics Screen 2024 edition? Tom's Amazing Statisics Viewer? 

If a mod modifies vanilla behavior, it also becomes that mod's responsiblity to ensure other mods don't break. Either way this is a pointless discussion as DeathLog is still perfectly usable through the keybind

**Comment by ItsProfessional** [comment]
Can you add it to the settings screen of the mod atleast? I really don't like adding unnecessary keybinds for opening mod screens

**Comment by Noaaan** [comment]
Like any other keybind it should be present in the Controls screen

**Comment by ItsProfessional** [comment]
?????? that's not what I asked at all.
I asked him to add a button to open the deathlog screen in the settings screen when you open it in mod menu.
Not "how do I set a keybind?"
