### ISSUE TITLE
cannot open minecraft AT ALL with death log

### ISSUE THREAD

**Issue by the-biggest-birfd** [glisco03/deathlog#33]
it just dosent launch no log, no nothing. 1.20.1 fabric, running on m1 mac

**Comment by BasiqueEvangelist** [comment]
Can you manually install https://modrinth.com/mod/owo-lib?

**Comment by BasiqueEvangelist** [comment]
Also, do you have any logs?
As in, is the logfile just not present at all, or does it stop somewhere after the first log messages?

**Comment by the-biggest-birfd** [comment]
no, it just says "waiting for output log" and doesn't do anything. lemme try owo lib rq

**Comment by the-biggest-birfd** [comment]
thanks, it works now
