### ISSUE TITLE
[Suggestion] Death replay

### ISSUE THREAD

**Issue by mitsuki-kagamin** [glisco03/deathlog#34]
add something like a replay of the last minute before death.

**Comment by gliscowo** [comment]
Hey, thanks for your suggestion! 

While this is certainly a neat idea, I'm afraid it'd be going significantly out-of-scope for DeathLog - doing this would required basically implementing the [Replay Mod](https://www.replaymod.com) in DeathLog, which doesn't make a whole lot of sense in my opinion.

As I see it, you can already use a tool like that instead. For one, you could simply always have the Replay Mod recording and simply look at the replay of your death when required, or alternatively use something like [OBS' Replay Buffer](https://obsproject.com/forum/resources/how-to-setup-instant-replay-in-obs-studio.613/) to have a rolling screen recording you can use the get a replay of your death that way


Either way, I'll be closing this issue as this isn't a feature I'll be implementing in DeathLog directly
Cheers
