### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by Fabian42** [glisco03/deathlog#35]
Just so this is documented.

I don't fully rely on this mod, but it helps to figure out what to command-give people after they bug-died, so I advertise it everywhere usually. Can't do that if it doesn't work! ;)

**Comment by alien-sunset** [comment]
same here, it's one of my most suggested mods, and people stuck on Realms servers can't avoid getting updated and now have to go without :(

**Comment by Noaaan** [comment]
Just released as of https://github.com/gliscowo/deathlog/releases/tag/0.3.2%2B1.20.3
