### ISSUE TITLE
Suggestion Player Leave

### ISSUE THREAD

**Issue by vaporvee** [glisco03/deathlog#4]
Can you add that it also makes these snapshots when a player logs out or when the server stops?
Idk if its possible to detect a server crash to backup the inventorys but this would also be cool

**Comment by gliscowo** [comment]
Hey, first of all apologies for the late response, I simply forgot to answer after I first say this issue. Regarding your request for backing up on leave and stop, those are not something that I personally think belongs in DeathLog as it is strictly designed to be a disaster-recovery and not a backup tool. Now this would perfectly match an inventory backup when the server crashes, however that is very difficult to properly and reliably implement and there are different tools that serve the same purpose. So at least for now, I'll close this issue but I might come back to it in the future
