### ISSUE TITLE
deathlog view kicking me from server

### ISSUE THREAD

**Issue by Saxostevesaxo** [glisco03/deathlog#44]
Hi when using this command in 1.21:
/deathlog view username
I get kicked from the server with error
internel exception: io.netty.handler.codec.decoderexception: Failed to decode packet 'clientbound/minecraft:custom_payload'

I have deathlog installed on both server and client.
the other commands seem to work ok.

Thanks

**Comment by Syntaxvgm** [comment]
I have this issue too.

**Comment by gliscowo** [comment]
Thanks for reporting this, I've now fixed it in [0.4.1 for 1.21](https://modrinth.com/mod/TPAYeAOc/version/lGjkPimB)

Cheers
