### ISSUE TITLE
[Bug] Crashes after removing Trinkets

### ISSUE THREAD

**Issue by supersaiyansubtlety** [glisco03/deathlog#5]
[server-crash](https://bpa.st/RRLA)

This occurs on startup (right before the game finishes launching) after having used and then removing [Trinkets](https://modrinth.com/mod/trinkets/version/FdJA5sbK).

**Comment by EGOIST1372** [comment]
@gliscowo Hi I see some warnings in my logs
 - Mod 'DeathLog' (deathlog) 0.2.7+1.18 recommends version 3.1.0 or later of trinkets, which is missing!
	 - You should install version 3.1.0 or later of trinkets for the optimal experience.

do I need to install trinkets as well?

**Comment by supersaiyansubtlety** [comment]
@EGOIST1372 That's just a `recommends` entry, it doesn't mean trinkets is required. 

This issue is for a crash that occurs if you've used deathlog+trinkets but then remove deathlog.
