### ISSUE TITLE
The interface does NOT shrink on the screen

### ISSUE THREAD

**Issue by QueenUlyana** [glisco03/deathlog#7]
The interface does NOT shrink on the screen. Version 1.18.1.
Could you make the left panel half the width?
My screen resolution is 1280x1024
![2022-03-18_12 13 56](https://user-images.githubusercontent.com/83131824/158975138-46eb8e4f-8f9f-42d7-bb61-95ea0d6fae92.png)

**Comment by gliscowo** [comment]
Hey, really sorry to have this be the response but there is currently not much I can do about this. I can understand your troubles, in fact this is a problem I spent quite some time thinking about during initial development. However, the way that MC's GUI system works these scrollable containers are sadly fixed to this size and would basically need to be completely rewritten if one wanted to remove that limitation. I might do that at some point, but at least for the time being I'll sadly have to close this issue as wontfix
Have a nice day
